In [1]:
import tensorflow as tf

##### The Data API

In [2]:
X = tf.range(10)
X

Metal device set to: Apple M1


2021-12-17 17:10:20.744296: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2021-12-17 17:10:20.744549: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [3]:
dataset = tf.data.Dataset.from_tensor_slices(X)
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [4]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


#####  Chaining Transformation

In [5]:
#dataset = dataset.batch(7).repeat(3)
dataset = dataset.repeat(3).batch(7)
for item in dataset:
    print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


In [6]:
dataset = dataset.map(lambda x: x * 2)
for item in dataset:
    print(item)

tf.Tensor([ 0  2  4  6  8 10 12], shape=(7,), dtype=int32)
tf.Tensor([14 16 18  0  2  4  6], shape=(7,), dtype=int32)
tf.Tensor([ 8 10 12 14 16 18  0], shape=(7,), dtype=int32)
tf.Tensor([ 2  4  6  8 10 12 14], shape=(7,), dtype=int32)
tf.Tensor([16 18], shape=(2,), dtype=int32)


2021-12-17 17:10:31.767100: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


In [7]:
dataset = dataset.apply(tf.data.experimental.unbatch())
for item in dataset:
    print(item)

Instructions for updating:
Use `tf.data.Dataset.unbatch()`.
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=

In [8]:
dataset = dataset.filter(lambda x: x < 10)
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


In [9]:
for item in dataset.batch(5):
    print(item)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


##### Shuffling the Data

In [10]:
dataset = tf.data.Dataset.range(10).repeat(3)
dataset = dataset.shuffle(buffer_size=5, seed=42).batch(7)
for item in dataset:
    print(item)

tf.Tensor([0 2 3 6 7 9 4], shape=(7,), dtype=int64)
tf.Tensor([5 0 1 1 8 6 5], shape=(7,), dtype=int64)
tf.Tensor([4 8 7 1 2 3 0], shape=(7,), dtype=int64)
tf.Tensor([5 4 2 7 8 9 9], shape=(7,), dtype=int64)
tf.Tensor([3 6], shape=(2,), dtype=int64)


In [11]:
dataset = tf.data.Dataset.range(10).repeat(3)
dataset = dataset.shuffle(buffer_size=5, seed=42).batch(7)
for item in dataset:
    print(item)

tf.Tensor([0 2 3 6 7 9 4], shape=(7,), dtype=int64)
tf.Tensor([5 0 1 1 8 6 5], shape=(7,), dtype=int64)
tf.Tensor([4 8 7 1 2 3 0], shape=(7,), dtype=int64)
tf.Tensor([5 4 2 7 8 9 9], shape=(7,), dtype=int64)
tf.Tensor([3 6], shape=(2,), dtype=int64)


##### test interleaving multi files

In [12]:
import numpy as np
import pandas as pd

In [13]:
def generate_multi_rand_csv(size):
    dir_path = './data/multi-rand-csv/'
    file_tmpl = 'file-{}.csv'
    df = pd.DataFrame(np.random.randn(10, 5))
    for i in range(size):
        df_i = df.copy()
        df_i['file'] = i
        file_path = dir_path + file_tmpl.format(i)
        df_i.to_csv(file_path)#, index=False)

In [14]:
generate_multi_rand_csv(20)

In [20]:
file_dataset = tf.data.Dataset.list_files('./data/multi-rand-csv/file-*.csv')
file_dataset

<ShuffleDataset shapes: (), types: tf.string>

In [27]:
for file_item in file_dataset.take(3):
    print(file_item)

tf.Tensor(b'./data/multi-rand-csv/file-8.csv', shape=(), dtype=string)
tf.Tensor(b'./data/multi-rand-csv/file-1.csv', shape=(), dtype=string)
tf.Tensor(b'./data/multi-rand-csv/file-17.csv', shape=(), dtype=string)


In [22]:
n_readers = 4
dataset = file_dataset.interleave(
    lambda filepath: tf.data.TextLineDataset(filepath).skip(1),
    cycle_length=n_readers)

In [26]:
for line in dataset.take(10):
    print(line)

tf.Tensor(b'0,1.2807214201858248,1.4253840264420519,-0.6209461042979402,0.2500863220852479,-2.5131070597123633,0', shape=(), dtype=string)
tf.Tensor(b'0,1.2807214201858248,1.4253840264420519,-0.6209461042979402,0.2500863220852479,-2.5131070597123633,4', shape=(), dtype=string)
tf.Tensor(b'0,1.2807214201858248,1.4253840264420519,-0.6209461042979402,0.2500863220852479,-2.5131070597123633,19', shape=(), dtype=string)
tf.Tensor(b'0,1.2807214201858248,1.4253840264420519,-0.6209461042979402,0.2500863220852479,-2.5131070597123633,16', shape=(), dtype=string)
tf.Tensor(b'1,0.7100440030857657,0.6679281545587905,1.3182660185087884,0.5353127292112103,-0.6269608968443804,0', shape=(), dtype=string)
tf.Tensor(b'1,0.7100440030857657,0.6679281545587905,1.3182660185087884,0.5353127292112103,-0.6269608968443804,4', shape=(), dtype=string)
tf.Tensor(b'1,0.7100440030857657,0.6679281545587905,1.3182660185087884,0.5353127292112103,-0.6269608968443804,19', shape=(), dtype=string)
tf.Tensor(b'1,0.71004400308

In [29]:
n_inputs = 6
def preprocess(line):
    defs = [0.] * n_inputs + [tf.constant([], dtype=tf.float32)] 
    fields = tf.io.decode_csv(line, record_defaults=defs)
    x = tf.stack(fields[:-1])
    y = tf.stack(fields[-1:])
    return x, y

In [31]:
for line in dataset.take(1):
    x, y = preprocess(line)
    print(x)
    print(y)

tf.Tensor([ 0.         1.2807214  1.425384  -0.6209461  0.2500863 -2.513107 ], shape=(6,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)


In [38]:
n_parse_threads = 3
shuffle_buffer_size = 1000
repeat = 1
batch_size = 32
n_readers = 4
dataset = file_dataset.interleave(
        lambda filepath: tf.data.TextLineDataset(filepath).skip(1),
        cycle_length=n_readers)
dataset = dataset.map(preprocess, num_parallel_calls=n_parse_threads)
dataset = dataset.shuffle(shuffle_buffer_size).repeat(repeat)
dataset = dataset.batch(batch_size).prefetch(1)

In [39]:
for X, Y in dataset:
    print(X)
    print(Y)

tf.Tensor(
[[ 9.         -1.3595622   0.17365299 -1.2531263   0.39650756  1.3467252 ]
 [ 8.         -0.12002534  0.8832705   1.5561962   0.17721292 -1.1692287 ]
 [ 2.          0.29781866 -0.8214921  -1.1314056   0.9418739   1.543451  ]
 [ 3.         -1.864165    0.94910604 -2.204692    1.1785688   1.0694499 ]
 [ 3.         -1.864165    0.94910604 -2.204692    1.1785688   1.0694499 ]
 [ 9.         -1.3595622   0.17365299 -1.2531263   0.39650756  1.3467252 ]
 [ 6.          1.2791651  -0.55894595 -0.55245787  0.49046767 -0.7541552 ]
 [ 5.         -0.22631189  1.1988922  -1.6093302  -0.09240708  1.404909  ]
 [ 4.         -1.1309483   0.28959596 -1.3947067   0.78634787 -0.15111268]
 [ 5.         -0.22631189  1.1988922  -1.6093302  -0.09240708  1.404909  ]
 [ 9.         -1.3595622   0.17365299 -1.2531263   0.39650756  1.3467252 ]
 [ 5.         -0.22631189  1.1988922  -1.6093302  -0.09240708  1.404909  ]
 [ 8.         -0.12002534  0.8832705   1.5561962   0.17721292 -1.1692287 ]
 [ 9.         

##### split California dataset to multi csv files

In [41]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing = fetch_california_housing()

In [43]:
housing.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [44]:
housing.target.reshape(-1, 1)

array([[4.526],
       [3.585],
       [3.521],
       ...,
       [0.923],
       [0.847],
       [0.894]])

In [45]:
X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target.reshape(-1, 1), random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, random_state=42)

In [47]:
scaler = StandardScaler()
scaler.fit(X_train)
X_mean = scaler.mean_
X_std = scaler.scale_
print(X_mean, X_std)

[ 3.89175860e+00  2.86245478e+01  5.45593655e+00  1.09963474e+00
  1.42428122e+03  2.95886657e+00  3.56464315e+01 -1.19584363e+02] [1.90927329e+00 1.26409177e+01 2.55038070e+00 4.65460128e-01
 1.09576000e+03 2.36138048e+00 2.13456672e+00 2.00093304e+00]
